exclude_patterns:
 - docs/*
 - tests/*
 - vendor/*
 - phpunit.*
rules:
 git.user_specific_ignored_file:
  enabled: false
 symfony.include_statement_used:
  enabled: true
  allowed_paths: [src/class/Log.php]
