exclude_patterns:
 - docs/*
 - tests/*
 - vendor/*
 - phpunit.*
rules:
 git.user_specific_ignored_file:
  enabled: false
 symfony.include_statement_used: # required for Alo::includeifexists() and Alo::includeonceifexists()
  enabled: false
 php.use_global_variable_or_function: #Implementation of getallheaders() for Windows users
  enabled: false
