exclude_patterns:
 - tests/*
 - vendor/*
 - phpunit.*
rules:
 git.user_specific_ignored_file:
  enabled: false
 symfony.include_statement_used: # required for Alo::includeifexists() and Alo::includeonceifexists()
  enabled: false
